PARAM_PATH  = '../param/'
DATA_PATH   = '../data/'
TRAIN_PROP  = 0.8
EVAL_PROP   = 0.1

ROWS = 16
COLUMES = 16

FLOW_INPUT_LEN = 12
FLOW_INPUT_DIM = 3
FLOW_OUTPUT_LEN = 3
FLOW_OUTPUT_DIM = 2

FLOW_INPUT_PRE_DAYS = 4
FLOW_INPUT_PRE_DAYS_KERNEL = 3